---
default_config:

logger:
  default: info
  logs:
    custom_components.givenergy_local: debug

# If you need to debug uncomment the line below
# Doc: https://www.home-assistant.io/integrations/debugpy/
debugpy:
